config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :end_users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  end


  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :end_users, only: [:index, :show, :edit, :update]
  end


  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    get "search" => "searches#search"
    get 'end_users/withdraw_confirm' => 'end_users#withdraw_confirm', as: 'withdraw_confirm'
    patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    resources :diaries, only: [:create, :index, :show, :edit, :update, :destroy]

    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources:post_comments, only: [:create, :destroy]
      resource:favorites, only: [:create, :destroy]
    end

    resources :end_users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
      end
    end

    resources :chat_rooms, only: [:new, :create, :index, :show, :destroy] do
      resources :chat_messages, only: [:create, :destroy]
      resources :room_users, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diaries, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :room_users, class_name: 'RoomUser',foreign_key: 'end_user_id', dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :favorited_posts, through: :favorites, source: :post
  has_many :chat_users, through: :room_users, source: :chat_room
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :profile_image

  validates :nick_name, presence:true, length: { minimum:2, maximum:15 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(end_user_id)
    active_relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    active_relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(nick_name: 'guestuser', email: 'guest@example.com', date_of_birth: '1968-5-5') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.nick_name = "guestuser"
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @end_user = EndUser.where("nick_name LIKE?", "#{word}")
    elsif search == "forward_match"
      @end_user = EndUser.where("nick_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @end_user = EndUser.where("nick_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @end_user = EndUser.where("nick_name LIKE?","%#{word}%")
    else
      @end_user = EndUser.all
    end
  end

  enum gender: { gender_private: 0, male: 1, female: 2, others: 3 }
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @end_users = EndUser.page(params[:page]).order(created_at: :desc)
  end

  def show
    @end_user = EndUser.find(params[:id])
    @posts = @end_user.posts.all
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path
    else
      render :edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(:nick_name, :gender, :date_of_birth, :introduction, :is_deleted, :email, :encrypted_password, :profile_image)
  end
end

app/controllers/end_users/sessions_controller.rb
class EndUsers::SessionsController < Devise::SessionsController
  def guest_sign_in
    end_user = EndUser.guest
    sign_in end_user
    redirect_to root_path, notice: 'guestuserでログインしました。'
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/_info.html.erb
<table class="table h5">
  <% if end_user.nick_name != "guestuser" %>
    <tbody>
      <tr>
        <td>
          <%= image_tag end_user.get_profile_image, size:'150x150' %><br>
          <strong><%= end_user.nick_name %></strong>
          <%= link_to '編集', edit_admin_end_user_path(@end_user), class: 'btn btn-success m-1' %>
        </td>
      </tr>
      <tr>
        <td>
          <%= "#{end_user.date_of_birth.strftime('%Y年%m月%d日')} (#{(Date.current.strftime('%Y%m%d').to_i - end_user.date_of_birth.strftime('%Y%m%d').to_i) / 10000})" %><br>
          性別：<%= end_user.gender_i18n %>
        </td>
      </tr>
      <tr>
        <td>
          <% if end_user.introduction.present? %>
            <%= end_user.introduction %>
          <% else %>
            自己紹介文がありません。
          <% end %>
        </td>
      </tr>
    <% else %>
      <tr>
        <td>
          <%= image_tag end_user.get_profile_image, size:'150x150' %><br>
          <strong><%= end_user.nick_name %></strong>
        </td>
      </tr>
      <tr>
        <td>
          xx年xx月xx日(xx)<br>
          性別：未登録
        </td>
      </tr>
      <tr>
        <td>新規登録するとここに自己紹介文が書き込めます。</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/end_users/edit.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-12 text-center">
      <h1><strong>プロフィール編集画面</strong></h1>
    </div>
    <div class="col-12 text-center">
      <%= form_with model: @end_user, url: admin_end_user_path, method: :patch, local:true do |f| %>

      <div class="form-group">
        <%= f.label :'メールアドレス' %><br>
        <%= f.email_field :email %>
      </div>

      <div class="form-group">
        <%= f.label :'プロフィール画像' %><br>
        <%= f.file_field :profile_image %>
      </div>

      <div class="form-group">
        <%= f.label :'ニックネーム' %><br>
        <%= f.text_field :nick_name %>
      </div>

      <div class="form-group">
        <%= f.label :'自己紹介' %><br>
        <%= f.text_area :introduction %>
      </div>

      <div class="form-group", onClick="alert('会員ステータスを変更しますか？')">
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
      </div>

      <div class="form-group">
        <%= f.radio_button :gender, EndUser.genders.key(0) %>
        <%= f.label :gender, EndUser.genders_i18n[:gender_private], value: EndUser.genders.key(0) %>

        <%= f.radio_button :gender, EndUser.genders.key(1) %>
        <%= f.label :gender, EndUser.genders_i18n[:male], value: EndUser.genders.key(1) %>

        <%= f.radio_button :gender, EndUser.genders.key(2) %>
        <%= f.label :gender, EndUser.genders_i18n[:female], value: EndUser.genders.key(1) %>

        <%= f.radio_button :gender, EndUser.genders.key(3) %>
        <%= f.label :gender, EndUser.genders_i18n[:others], value: EndUser.genders.key(1) %>
      </div>

      <div class="form-group">
        <%= f.label :'生年月日' %><br>
        <%= f.date_select :date_of_birth, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 55), default: Date.new(1960, 1, 1) %>
      </div>

      <div class="form-group">
        <%= f.submit '更新する', class: 'btn btn-info' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/end_users/index.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-12 text-center pb-4">
      <%= render 'public/searches/search', range: @range %>
      <h1 class="pt-4"><strong>会員一覧</strong></h1>
    </div>

    <% @end_users.each do |end_user| %>
      <% if end_user.nick_name != "guestuser" %>
        <div class="col-lg-4 text-center p-2">
          <h4>
            <%= link_to admin_end_user_path(end_user) do %>
              <%= image_tag end_user.get_profile_image, size: '200x200', class: 'rounded-circle' %><br>
              <%= end_user.nick_name %><br>
            <% end %>
          </h4>
          <h5>
            <% if end_user.introduction.present? %>
              <%= end_user.introduction.truncate(20, omission: '...') %>
            <% else %>
              自己紹介がありません
            <% end %>
          </h5>
          <% if end_user.is_deleted %>
            <p class="text-danger">退会</p>
          <% else %>
            <p class="text-success">有効</p>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <div class="col-12 text-center pt-4">
      <%= paginate @end_users %>
    </div>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="text-center p-2">
  <h3 class="text-light" style="background-color: #3cb371; border-radius: 5px;"><%= flash[:notice] %></h3>
  <h3 class="text-light" style="background-color: #dc143c; border-radius: 5px;"><%= flash[:alert] %></h3>
</div>
<div class="container p-5">
  <div class="row">
    <div class="col">
      <% if @end_user != current_end_user %>
        <%= link_to end_users_path, class: 'btn btn-secondary' do %>
          <i class="fa-solid fa-arrow-left"></i> 前のページに戻る
        <% end %>
      <% end %>
    </div>
    <div class="col-12 text-center h1">
      <strong><%= @end_user.nick_name %>さんのマイページ</strong>
    </div>
    <div class="col-lg-4 pt-4">
      <h3>会員情報</h3>
      <%= render 'info', end_user: @end_user %>
    </div>
    <div class="col-lg-8">
      <h3 class="pt-4">
        <%= @end_user.nick_name %>さんの投稿一覧
      </h3>
      <table class="table border">
        <thead style="background-color: #fffacd;">
          <th width="150px">タイトル</th>
          <th class="none" width="300px">内容</th>
          <th colspan="3" width="100px"></th>
        </thead>
        <tbody style="background-color: #ffffff;">
          <% @posts.each do |post| %>
            <tr>
              <td width="150px"><%= post.title %></td>
              <td class="none" width="300px"><%= post.body.truncate(15, omission: '...') %></td>
              <td width="100px">
                <%= link_to post_path(post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-outline-danger text-center", remote: true do %>
                  <i class="fa-solid fa-trash-can"></i> <span class="none">削除</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>