config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :end_users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  end


  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :end_users, only: [:index, :show, :edit, :update]
  end


  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    get "search" => "searches#search"
    get 'end_users/withdraw_confirm' => 'end_users#withdraw_confirm', as: 'withdraw_confirm'
    patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    resources :diaries, only: [:create, :index, :show, :edit, :update, :destroy]

    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources:post_comments, only: [:create, :destroy]
      resource:favorites, only: [:create, :destroy]
    end

    resources :end_users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
      end
    end

    resources :chat_rooms, only: [:new, :create, :index, :show, :destroy] do
      resources :chat_messages, only: [:create, :destroy]
      resources :room_users, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin-header.html.erb
<header class="border-bottom border-dark" style="background-color: #faf0e6;">
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-dark">
      <a class="navbar-brand text-dark m-2" href="/admin/homes/top">
        <%= image_tag 'mydiary.jpg', size: "150x85"%>
        管理者ページ
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to root_path, class:'nav-link text-light btn btn-dark ml-2' do %>
              <i class="fa-solid fa-house-user"></i> 会員Home
            <% end %>
          </li>
          <li>
            <%= link_to admin_homes_top_path, class:'nav-link text-light btn btn-dark ml-2' do %>
              <i class="fa-solid fa-house"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to admin_end_users_path, class:'nav-link text-light btn btn-dark ml-2' do %>
              <i class="fa-solid fa-users"></i> 会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class:'nav-link text-light btn btn-dark ml-2' do %>
              <i class="fa-solid fa-right-from-bracket"></i> ログアウト
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="border-top border-dark" style="background-color: #faf0e6;">
  <div class='container pt-3'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>© My Diary 2023</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom border-dark" style="background-color: #faf0e6;">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand text-dark m-2" href="/">
        <%= image_tag 'mydiary.jpg', size: "150x85"%>
      </a>
      <button class="navbar-toggler bg-dark" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if end_user_signed_in? %>
          <li class="nav-item">
            <%= link_to chat_rooms_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-regular fa-comments"></i> チャット
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to posts_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-solid fa-pen-to-square"></i> 投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to end_users_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-solid fa-users"></i> 会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to end_user_path(current_end_user), class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-solid fa-user"></i> マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_end_user_session_path, method: :delete, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-solid fa-right-from-bracket"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%=  link_to root_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-solid fa-house"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to homes_about_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%=  link_to new_end_user_registration_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_end_user_session_path, class:'nav-link text-light btn btn-dark m-1' do %>
              <i class="fa-solid fa-right-to-bracket"></i> ログイン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to end_users_guest_sign_in_path, class: "nav-link text-light btn btn-dark m-1", method: :post do %>
              <i class="fa-solid fa-right-to-bracket"></i> ゲストログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Diary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/7fa8fafe4f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
  </head>

  <body>
    <% if request.fullpath.include? "/admin" %>
      <%= render 'layouts/admin-header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>